import {
  PersonalInfo,
  NavigationItem,
  SocialLink,
  Education,
  Experience,
  Skill,
  Project,
  Certification,
} from "@/types/index";

export const personalInfo: PersonalInfo = {
  name: "Lucas Samuel Pereira Godoy",
  title: "Desenvolvedor Full-Stack",
  bio: "Desenvolvedor Full-stack | Especialista em sistemas de gestão para o setor público. Domínio de PHP (Laravel, CodeIgniter), Java (Spring Boot) e front-end moderno (React.js, Next.js, Tailwind, Bootstrap, JavaScript/TypeScript). Experiência em DDD, Clean Architecture, Microsserviços, bancos de dados MySQL/PostgreSQL e DevOps (Docker, CI/CD, GitHub Actions). Apaixonado por criar soluções que modernizam e automatizam processos.",
  location: "Palmital, Paraná, Brasil - CEP: 85270-000",
  email: "lukassamuka88@gmail.com",
  phone: "+5542998300659",
  avatar: "/avatar.png",
  resume: "/documents/lucas-samuel-pereira-curriculo.pdf",
  timezone: "America/Sao_Paulo",
  languages: [
    { language: "Português", level: "Nativo/Fluente" },
    { language: "Inglês", level: "Intermediário" },
  ],
  interests: [
    "Desenvolvimento Web",
    "Sistemas de Gestão",
    "Automação de Processos",
    "Full-Stack Development",
    "Arquitetura de Software",
    "Clean Code",
    "Domain Driven Design",
  ],
  availability: "available",
};

export const navigationItems: NavigationItem[] = [
  { label: "Início", href: "#hero" },
  { label: "Sobre", href: "#about" },
  { label: "Experiência", href: "#experience" },
  { label: "Habilidades", href: "#skills" },
  { label: "Projetos", href: "#projects" },
  { label: "Certificações", href: "#certifications" },
  { label: "Contato", href: "#contact" },
];

export const socialLinks: SocialLink[] = [
  {
    platform: "LinkedIn",
    url: "https://linkedin.com/in/lucas-samuel-pereira-godoy",
    icon: "Linkedin",
    username: "lucas-samuel-pereira-godoy",
  },
  {
    platform: "GitHub",
    url: "https://github.com/lucassamuel97",
    icon: "Github",
    username: "lucassamuel97",
  },
  {
    platform: "Email",
    url: "mailto:lukassamuka88@gmail.com",
    icon: "Mail",
    username: "lukassamuka88@gmail.com",
  },
  {
    platform: "WhatsApp",
    url: "https://wa.me/5542998300659",
    icon: "WhatsApp",
    username: "+5542998300659",
  },
];

export const education: Education[] = [
  {
    id: "1",
    degree: "Tecnólogo em Sistemas para Internet",
    institution: "Universidade Tecnológica Federal do Paraná",
    institutionUrl: "https://utfpr.edu.br",
    location: "Guarapuava, Paraná, Brasil",
    period: {
      start: new Date("2017-07-05"),
      end: new Date("2022-12-31"),
    },
    description:
      "Curso superior voltado ao desenvolvimento web, abrangendo programação, arquitetura de software, bancos de dados, redes e sistemas distribuídos. Ênfase em práticas modernas e projetos aplicados ao setor de tecnologia.",
    relevantCourses: [
      "Algoritmos e Lógica de Programação",
      "Estruturas de Dados",
      "Programação Orientada a Objetos",
      "Desenvolvimento de Sistemas",
      "Banco de Dados",
      "Programação Web",
      "Arquitetura de Software",
      "Engenharia de Software",
      "Redes de Computadores",
      "Sistemas Distribuídos",
      "Redes de Computadores e Internet",
      "Estágio Curricular Obrigatório",
    ],
  },
  {
    id: "2",
    degree: "Tecnólogo em Gestão da Tecnologia da Informação",
    institution: "UCP - Faculdades do Centro do Paraná",
    location: "Pitanga, Paraná, Brasil",
    period: {
      start: new Date("2015-02-01"),
      end: new Date("2017-06-30"),
    },
    description:
      "Formação superior focada em administração de sistemas, infraestrutura de TI, segurança da informação e gestão de projetos. Preparação para atuação em ambientes corporativos e públicos.",
    relevantCourses: [
      "Gestão de Projetos",
      "Infraestrutura de TI",
      "Segurança da Informação",
      "Redes de Computadores",
      "Sistemas Operacionais",
      "Desenvolvimento Web",
      "Banco de Dados",
      "Análise de Sistemas",
    ],
  },
];

export const experiences: Experience[] = [
  {
    id: "1",
    title: "Full-stack Developer",
    company: "Boeing e Rocha",
    companyUrl: "",
    location: "Paraná, Brasil",
    period: {
      start: new Date("2018-03-01"),
      end: null, // Emprego atual
    },
    description:
      "Desenvolvedor Full-stack com experiência no desenvolvimento de ponta a ponta de sistemas de gestão para o setor público. Especializado no ecossistema PHP (PHP puro, Laravel, CodeIgniter) e tecnologias front-end (JavaScript, jQuery, Bootstrap, Tailwind, Next.js) para criar soluções que modernizam e automatizam processos.",
    responsibilities: [
      "Responsável pelo levantamento de requisitos, desenvolvimento, manutenção de sistemas legados e suporte ao usuário final",
      "Desenvolvimento de sistemas de gestão para a Assistência Social que centralizam dados de múltiplas unidades",
      "Automação da geração de relatórios mensais (RMA) e implementação de visualização de dados com georreferenciamento",
      "Criação de aplicação para monitoramento de contratos públicos que automatizou o acompanhamento de prazos",
      "Integração com SIM-AM e implementação de notificações por e-mail para reduzir riscos de inconformidade",
      "Manutenção e evolução de sistema para postos de saúde, implementando novos módulos (agendamento, estoque)",
      "Garantia da escalabilidade do projeto ao seguir a arquitetura HMVC",
    ],
    technologies: [
      "PHP",
      "Laravel",
      "CodeIgniter",
      "MySQL",
      "JavaScript",
      "jQuery",
      "Bootstrap",
      "Tailwind",
      "Ajax",
      "Git",
      "Next.js",
      "Trello",
    ],
    type: "full-time",
    achievements: [
      "Desenvolveu sistema de gestão para Assistência Social que centralizou dados de múltiplas unidades",
      "Automatizou geração de relatórios mensais (RMA) e implementou visualização de dados com georreferenciamento",
      "Criou aplicação para monitoramento de contratos públicos com integração SIM-AM e notificações automáticas",
      "Manteve e evoluiu sistema para postos de saúde seguindo arquitetura HMVC",
    ],
  },
  {
    id: "2",
    title: "Assistente Administrativo",
    company: "Supermercado Oeste",
    companyUrl: "",
    location: "Paraná, Brasil",
    period: {
      start: new Date("2014-01-01"),
      end: new Date("2018-01-31"),
    },
    description:
      "Atuei na gestão de dados essenciais para a operação do negócio, sendo responsável pelo ciclo de vida das informações de produtos, clientes e fornecedores no sistema.",
    responsibilities: [
      "Garantia da consistência e precisão dos dados através do cadastro e da precificação correta de mercadorias",
      "Controle de inventário por meio da contagem de estoque",
      "Gestão de dados de produtos, clientes e fornecedores no sistema",
      "Processos críticos que impactavam diretamente as áreas de compras e vendas da empresa",
    ],
    technologies: [
      "Sistemas de Gestão",
      "Controle de Estoque",
      "Gestão de Dados",
    ],
    type: "full-time",
  },
];

export const skills: Skill[] = [
  // Frontend
  {
    id: "1",
    name: "HTML5",
    category: "frontend",
    level: 95,
    icon: "html5",
    experience: "6 anos",
  },
  {
    id: "2",
    name: "CSS3",
    category: "frontend",
    level: 90,
    icon: "css3",
    experience: "6 anos",
  },
  {
    id: "3",
    name: "JavaScript",
    category: "frontend",
    level: 90,
    icon: "javascript",
    experience: "6 anos",
    projects: ["project-1", "project-2", "project-3"],
  },
  {
    id: "4",
    name: "TypeScript",
    category: "frontend",
    level: 80,
    icon: "typescript",
    experience: "2 anos",
    projects: ["project-1", "project-2"],
  },
  {
    id: "5",
    name: "React",
    category: "frontend",
    level: 80,
    icon: "react",
    experience: "2 anos",
    projects: ["project-1", "project-2"],
  },
  {
    id: "6",
    name: "Next.js",
    category: "frontend",
    level: 85,
    icon: "nextjs",
    experience: "2 anos",
    projects: ["project-1", "project-2"],
  },
  {
    id: "7",
    name: "jQuery",
    category: "frontend",
    level: 85,
    icon: "jquery",
    experience: "6 anos",
    projects: ["project-1", "project-2", "project-3"],
  },
  {
    id: "8",
    name: "Bootstrap",
    category: "frontend",
    level: 92,
    icon: "bootstrap",
    experience: "6 anos",
    projects: ["project-1", "project-2", "project-3"],
  },
  {
    id: "9",
    name: "Tailwind CSS",
    category: "frontend",
    level: 85,
    icon: "tailwind",
    experience: "2 anos",
    projects: ["project-1", "project-2"],
  },
  {
    id: "10",
    name: "Material UI",
    category: "frontend",
    level: 54,
    icon: "materialui",
    experience: "1 ano",
    projects: ["project-1", "project-2"],
  },
  {
    id: "11",
    name: "Sass/SCSS",
    category: "frontend",
    level: 75,
    icon: "sass",
    experience: "3 anos",
  },
  {
    id: "12",
    name: "Vue.js",
    category: "frontend",
    level: 45,
    icon: "vuejs",
    experience: "6 meses",
  },

  // Backend
  {
    id: "13",
    name: "PHP",
    category: "backend",
    level: 95,
    icon: "php",
    experience: "6 anos",
    projects: ["project-1", "project-2", "project-3"],
  },
  {
    id: "14",
    name: "Laravel",
    category: "backend",
    level: 95,
    icon: "laravel",
    experience: "4 anos",
    projects: ["project-1", "project-2"],
  },
  {
    id: "15",
    name: "CodeIgniter",
    category: "backend",
    level: 75,
    icon: "codeigniter",
    experience: "4 anos",
    projects: ["project-1", "project-3"],
  },
  {
    id: "16",
    name: "Java",
    category: "backend",
    level: 75,
    icon: "java",
    experience: "1 ano",
    projects: ["project-4"],
  },
  {
    id: "17",
    name: "Spring Boot",
    category: "backend",
    level: 85,
    icon: "springboot",
    experience: "1 ano",
    projects: ["project-4"],
  },
  {
    id: "18",
    name: "Node.js",
    category: "backend",
    level: 60,
    icon: "nodejs",
    experience: "1 ano",
  },
  {
    id: "19",
    name: "Express.js",
    category: "backend",
    level: 55,
    icon: "express",
    experience: "1 ano",
  },
  {
    id: "20",
    name: "REST APIs",
    category: "backend",
    level: 90,
    icon: "api",
    experience: "4 anos",
    projects: ["project-1", "project-2", "project-3"],
  },
  {
    id: "21",
    name: "Composer",
    category: "backend",
    level: 85,
    icon: "composer",
    experience: "4 anos",
  },

  // Database
  {
    id: "22",
    name: "MySQL",
    category: "database",
    level: 98,
    icon: "mysql",
    experience: "6 anos",
    projects: ["project-1", "project-2", "project-3"],
  },
  {
    id: "23",
    name: "PostgreSQL",
    category: "database",
    level: 80,
    icon: "postgresql",
    experience: "2 anos",
    projects: ["project-1", "project-2"],
  },
  {
    id: "24",
    name: "MongoDB",
    category: "database",
    level: 50,
    icon: "mongodb",
    experience: "1 ano",
    projects: ["project-4"],
  },
  {
    id: "25",
    name: "Firebase",
    category: "database",
    level: 60,
    icon: "firebase",
    experience: "1 ano",
    projects: ["project-5"],
  },
  {
    id: "26",
    name: "Redis",
    category: "database",
    level: 55,
    icon: "redis",
    experience: "1 ano",
  },
  {
    id: "27",
    name: "SQL",
    category: "database",
    level: 95,
    icon: "sql",
    experience: "6 anos",
    projects: ["project-1", "project-2", "project-3"],
  },

  // Mobile
  {
    id: "28",
    name: "Ionic",
    category: "mobile",
    level: 50,
    icon: "ionic",
    experience: "1 ano",
    projects: ["project-5"],
  },
  {
    id: "29",
    name: "Flutter",
    category: "mobile",
    level: 30,
    icon: "flutter",
    experience: "6 meses",
    projects: ["project-5"],
  },

  // DevOps
  {
    id: "30",
    name: "Docker",
    category: "devops",
    level: 80,
    icon: "docker",
    experience: "1 ano",
  },
  {
    id: "31",
    name: "GitHub Actions",
    category: "devops",
    level: 70,
    icon: "githubactions",
    experience: "1 ano",
  },
  {
    id: "32",
    name: "Travis CI",
    category: "devops",
    level: 60,
    icon: "travis",
    experience: "1 ano",
  },
  {
    id: "33",
    name: "CI/CD",
    category: "devops",
    level: 70,
    icon: "cicd",
    experience: "1 ano",
  },
  {
    id: "34",
    name: "RabbitMQ",
    category: "devops",
    level: 75,
    icon: "rabbitmq",
    experience: "1 ano",
  },
  {
    id: "35",
    name: "AWS",
    category: "devops",
    level: 40,
    icon: "aws",
    experience: "1 ano",
  },
  {
    id: "36",
    name: "Linux",
    category: "devops",
    level: 80,
    icon: "linux",
    experience: "4 anos",
  },
  {
    id: "37",
    name: "Apache",
    category: "devops",
    level: 75,
    icon: "apache",
    experience: "3 anos",
  },
  {
    id: "38",
    name: "Nginx",
    category: "devops",
    level: 45,
    icon: "nginx",
    experience: "1 anos",
  },

  // Tools
  {
    id: "39",
    name: "Git",
    category: "tools",
    level: 85,
    icon: "git",
    experience: "6 anos",
  },
  {
    id: "40",
    name: "Visual Studio Code",
    category: "tools",
    level: 85,
    icon: "vscode",
    experience: "3 anos",
  },
  {
    id: "41",
    name: "Cursor",
    category: "tools",
    level: 85,
    icon: "cursor",
    experience: "1 ano",
  },
  {
    id: "42",
    name: "Postman",
    category: "tools",
    level: 80,
    icon: "postman",
    experience: "2 anos",
  },
  {
    id: "43",
    name: "Figma",
    category: "tools",
    level: 60,
    icon: "figma",
    experience: "1 ano",
  },
  {
    id: "44",
    name: "Swagger",
    category: "tools",
    level: 70,
    icon: "swagger",
    experience: "1 ano",
  },
  {
    id: "45",
    name: "Trello",
    category: "tools",
    level: 90,
    icon: "trello",
    experience: "6 anos",
  },
  {
    id: "46",
    name: "ESLint",
    category: "tools",
    level: 75,
    icon: "eslint",
    experience: "2 anos",
  },
  {
    id: "47",
    name: "Prettier",
    category: "tools",
    level: 80,
    icon: "prettier",
    experience: "2 anos",
  },
  {
    id: "48",
    name: "Webpack",
    category: "tools",
    level: 60,
    icon: "webpack",
    experience: "1 ano",
  },
  {
    id: "49",
    name: "Vite",
    category: "tools",
    level: 70,
    icon: "vite",
    experience: "1 ano",
  },

  // Arquitetura & Metodologias
  {
    id: "51",
    name: "DDD",
    category: "other",
    level: 90,
    icon: "ddd",
    experience: "3 anos",
  },
  {
    id: "52",
    name: "Clean Architecture",
    category: "other",
    level: 85,
    icon: "cleanarchitecture",
    experience: "3 anos",
  },
  {
    id: "53",
    name: "Microservices",
    category: "other",
    level: 60,
    icon: "microservices",
    experience: "1 ano",
  },
  {
    id: "54",
    name: "GraphQL",
    category: "other",
    level: 50,
    icon: "graphql",
    experience: "6 meses",
    projects: ["project-6"],
  },
  {
    id: "55",
    name: "PHPUnit",
    category: "other",
    level: 70,
    icon: "phpunit",
    experience: "2 anos",
  },
  {
    id: "56",
    name: "Jest",
    category: "other",
    level: 65,
    icon: "jest",
    experience: "1 ano",
  },
  {
    id: "57",
    name: "API Gateway",
    category: "other",
    level: 55,
    icon: "apigateway",
    experience: "1 ano",
  },
  {
    id: "58",
    name: "SOLID Principles",
    category: "other",
    level: 85,
    icon: "solid",
    experience: "3 anos",
  },
];

export const projects: Project[] = [
  {
    id: "project-4",
    title: "Admin Catálogo de Vídeo - SamucaFlix (Back-end)",
    description:
      "API para o painel administrativo de um catálogo de vídeos (SamucaFlix) com serviços RESTful robustos.",
    longDescription:
      "Desenvolvimento completo da API para o painel administrativo de um catálogo de vídeos (SamucaFlix). O projeto abordou a criação de serviços RESTful robustos, implementação de regras de negócio complexas, arquitetura da aplicação e integração com banco de dados, aplicando as melhores práticas de engenharia de software.",
    image: "",
    technologies: [
      "Java",
      "Spring Boot",
      "MySQL",
      "Clean Architecture",
      "DDD",
      "SOLID",
      "RabbitMQ",
      "Swagger",
      "Flyway",
      "Docker",
      "Docker Compose",
      "Keycloak",
      "Mockito",
      "JUnit",
      "JaCoCo",
      "Notification Pattern",
      "Test-Driven Development (TDD)",
      "API RESTful",
      "Microservices",
      "Git",
      "GitHub Actions",
      "CI/CD",
    ],
    githubUrl:
      "https://github.com/Lucassamuel97/admin-catalogo-de-videos-java-fc",
    liveUrl:
      "https://hub.docker.com/r/lucassamuel/admin-catalogo-de-videos-java-fc",
    category: "api",
    featured: false,
    status: "completed",
    createdAt: new Date("2024-05-29"),
    updatedAt: new Date("2025-03-12"),
  },
  {
    id: "project-5",
    title: "Admin Catálogo de Vídeo - SamucaFlix (Front-end)",
    description:
      "Painel administrativo para um catálogo de vídeos (SamucaFlix) com React.js.",
    longDescription:
      "Painel administrativo completo desenvolvido com React.js para gerenciamento de um catálogo de vídeos (SamucaFlix). O projeto abordou conceitos essenciais do ecossistema React, como arquitetura baseada em componentes, gerenciamento de estado, roteamento e integração com APIs.",
    image: "",
    technologies: [
      "React.js",
      "Vite",
      "Redux Toolkit",
      "Mock Service Worker (MSW)",
      "Material UI v7",
      "Testing Library",
      "Vitest",
    ],
    githubUrl: "https://github.com/Lucassamuel97/admin-videos-react",
    liveUrl: "",
    category: "web",
    featured: false,
    status: "completed",
    createdAt: new Date("2024-12-10"),
    updatedAt: new Date("2025-07-16"),
  },
  {
    id: "project-6",
    title: "Portal do Usuário - SamucaFlix (Front-end)",
    description:
      "Interface do usuário para a plataforma de streaming SamucaFlix com React.js.",
    longDescription:
      "Interface rica e interativa para usuários da plataforma de streaming SamucaFlix. O projeto envolveu a construção de uma aplicação moderna abordando conceitos como componentização, consumo de APIs para exibição de catálogos de vídeo, gerenciamento de estado da aplicação e roteamento.",
    image: "/projects/codeflix-portal.png",
    technologies: [
      "React.js",
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "Heroicons",
      "Vidstack React",
      "Maverick.js",
      "JSON Server",
      "Zod",
      "ESLint",
      "Prettier",
      "Jest",
      "Testing Library",
      "Turbopack",
    ],
    githubUrl: "https://github.com/Lucassamuel97/samucaflix-client",
    liveUrl: "https://samucaflix-client.vercel.app/",
    category: "web",
    featured: false,
    status: "completed",
    createdAt: new Date("2025-06-03"),
    updatedAt: new Date("2025-08-04"),
  },
  {
    id: "project-1",
    title: "Sistema de Gestão para Assistência Social",
    description:
      "Sistema que centralizou dados de múltiplas unidades, automatizou a geração de relatórios mensais (RMA) e implementou visualização de dados com georreferenciamento.",
    longDescription:
      "Sistema completo de gestão desenvolvido para a Assistência Social que revolucionou o gerenciamento de dados. Centralizou informações de múltiplas unidades em uma única plataforma, automatizou a geração de relatórios mensais (RMA) e implementou visualização de dados com georreferenciamento para melhor tomada de decisões.",
    image: "",
    technologies: [
      "PHP",
      "Laravel",
      "MySQL",
      "JavaScript",
      "jQuery",
      "Bootstrap",
      "Georreferenciamento",
      "Ajax",
    ],
    githubUrl: "",
    liveUrl: "",
    category: "web",
    featured: true,
    status: "completed",
    createdAt: new Date("2018-06-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "project-2",
    title: "Aplicação de Monitoramento de Contratos Públicos",
    description:
      "Aplicação que automatizou o acompanhamento de prazos através da integração com o SIM-AM e notificações por e-mail.",
    longDescription:
      "Sistema inovador para monitoramento de contratos públicos que automatizou completamente o acompanhamento de prazos. Integrou-se com o SIM-AM para sincronização automática de dados e implementou sistema de notificações por e-mail, reduzindo significativamente os riscos de inconformidade e melhorando a eficiência operacional.",
    image: "",
    technologies: [
      "PHP",
      "CodeIgniter",
      "MySQL",
      "JavaScript",
      "jQuery",
      "Bootstrap",
      "Integração SIM-AM",
      "Sistema de Notificações",
    ],
    githubUrl: "",
    liveUrl: "",
    category: "web",
    featured: true,
    status: "completed",
    createdAt: new Date("2019-03-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "project-3",
    title: "Sistema para Postos de Saúde",
    description:
      "Plataforma de gestão para postos de saúde, com módulos de agendamento e controle de estoque, desenvolvida em arquitetura HMVC.",
    longDescription:
      "Sistema completo para a gestão de postos de saúde, evoluído continuamente para atender novas demandas. Foram implementados módulos estratégicos como agendamento de consultas e controle de estoque de insumos médicos. Toda a solução foi construída com base na arquitetura HMVC, garantindo escalabilidade, organização do código e facilidade de manutenção a longo prazo.",
    image: "",
    technologies: [
      "PHP",
      "CodeIgniter",
      "MySQL",
      "JavaScript",
      "jQuery",
      "Bootstrap",
      "Arquitetura HMVC",
    ],
    githubUrl: "",
    liveUrl: "",
    category: "web",
    featured: true,
    status: "completed",
    createdAt: new Date("2018-09-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "project-7",
    title: "Examini - Sistema de Auditorias Públicas",
    description:
      "Plataforma para planejamento, execução e controle de auditorias públicas, focada em eficiência e transparência.",
    longDescription:
      "O Examini é um sistema desenvolvido para auxiliar auditores públicos em todas as etapas do processo de auditoria, desde o planejamento até o controle final. Sua interface intuitiva e recursos avançados tornam os processos mais organizados, ágeis e transparentes, permitindo que órgãos públicos reduzam o tempo gasto em tarefas administrativas, aumentem a precisão dos resultados e garantam maior eficiência na gestão das auditorias.",
    image: "",
    technologies: ["PHP", "Laravel", "MySQL", "Bootstrap"],
    githubUrl: "",
    liveUrl: "https://examini.site/",
    category: "web",
    featured: true,
    status: "in-progress",
    createdAt: new Date("2025-02-01"),
    updatedAt: new Date("2025-08-01"),
  },
  {
    id: "project-8",
    title: "Sistema de Controle de Manutenções Agrícolas",
    description:
      "Aplicação web para o controle de manutenções preventivas de colheitadeiras e tratores agrícolas.",
    longDescription:
      "Este projeto foi desenvolvido como Trabalho de Conclusão de Curso (TCC) no curso de Tecnologia em Sistemas para Internet da UTFPR. O objetivo principal é oferecer uma solução web que auxilie produtores rurais e gestores agrícolas no planejamento e controle das manutenções preventivas de colheitadeiras e tratores. A aplicação proporciona organização, redução de falhas mecânicas e maior eficiência operacional no campo.",
    image: "",
    technologies: [
      "Laravel",
      "PHP",
      "Bootstrap",
      "MySQL",
      "JavaScript",
      "HTML",
      "CSS",
      "Git",
      "Docker",
    ],
    githubUrl:
      "https://github.com/Lucassamuel97/tcc-preventive-maintenance-utfpr",
    liveUrl:
      "https://tcc.tsi.pro.br/uploads/academic_activity/pdf/132/GP_COINT_2022_1_LUCAS_SAMUEL_PEREIRA_GODOY_MONOGRAFIA.pdf",
    category: "web",
    featured: false,
    status: "completed",
    createdAt: new Date("2019-08-01"),
    updatedAt: new Date("2020-01-01"),
  },
  {
    id: "project-9",
    title: "Sistema de Rastreamento de Veículos",
    description:
      "Plataforma desenvolvida durante a Imersão Fullcycle 20 para rastreamento em tempo real de veículos.",
    longDescription:
      "Este projeto foi construído durante a Imersão Fullcycle 20 com foco no desenvolvimento de um sistema de rastreamento de veículos em tempo real. A solução integra múltiplos serviços, incluindo backend em NestJS, frontend em Next.js, mensageria com Kafka, banco de dados MongoDB e simulação de dados em Golang. Com suporte a Docker e microsserviços, o sistema permite acompanhar rotas e direções por meio da integração com APIs de mapas, oferecendo escalabilidade e desempenho em cenários reais de rastreamento.",
    image: "",
    technologies: [
      "NestJS",
      "Next.js",
      "Golang",
      "Kafka",
      "MongoDB",
      "Docker",
      "TypeScript",
    ],
    githubUrl: "https://github.com/Lucassamuel97/rastreamento-de-veiculos",
    liveUrl: "",
    category: "web",
    featured: false,
    status: "completed",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2025-06-01"),
  },
];

// Certificações e Conquistas
export const certifications: Certification[] = [
  {
    id: "1",
    title: "RabbitMQ",
    description:
      "Curso concluído sobre RabbitMQ, abordando conceitos fundamentais e avançados do sistema de mensageria para comunicação assíncrona entre processos.",
    organization: "Full Cycle",
    certificateCode: "2ef7f164-d78b-4d3d-90b9-3b7855da2d82",
    period: "28/06/2024 a 17/10/2024",
    hours: "6 horas",
    instructors: "Full Cycle, Wesley Willians",
    url: "https://fullcycle.com.br/certificado/2ef7f164-d78b-4d3d-90b9-3b7855da2d82",
  },
  {
    id: "2",
    title: "Java Continuous Integration-Delivery c. AWS e Github Actions",
    description:
      "Curso sobre Java Continuous Integration-Delivery com AWS e GitHub Actions, abordando práticas de CI/CD com foco em automação de deploys.",
    organization: "Udemy",
    instructors: "Leandro Costa, Erudio Training, Erudio Training Support",
    certificateCode: "UC-58588596-e91d-4b4b-82aa-228087c4e12f",
    period: "03/06/2024",
    hours: "18,5 horas",
    url: "https://www.udemy.com/certificate/UC-58588596-e91d-4b4b-82aa-228087c4e12f/"
  },
  {
    id: "3",
    title: "Comunicação entre Sistemas",
    description:
      "Curso sobre Comunicação entre Sistemas, abordando protocolos REST, gRPC e GraphQL para integração eficiente de aplicações.",
    organization: "Full Cycle",
    certificateCode: "3e5e5eb5-c256-42a8-b8b9-16a6eeffcf9e",
    period: "19/06/2024 a 23/07/2024",
    hours: "18 horas",
    instructors: "Full Cycle, Wesley Willians",
    url: "https://fullcycle.com.br/certificado/3e5e5eb5-c256-42a8-b8b9-16a6eeffcf9e",
  },
  {
    id: "4",
    title: "Clean Architecture",
    description:
      "Curso sobre Clean Architecture para alcançar reusabilidade de código, alta coesão, independência de tecnologia e facilidade de testes.",
    organization: "Full Cycle",
    certificateCode: "a5aaa14b-4538-4e42-ba2c-0adab4d36a14",
    period: "01/08/2024 a 09/08/2024",
    hours: "30 horas",
    instructors: "Full Cycle, Wesley Willians",
    url: "https://fullcycle.com.br/certificado/a5aaa14b-4538-4e42-ba2c-0adab4d36a14",
  },
  {
    id: "5",
    title: "Docker",
    description:
      "Curso sobre Docker com foco na criação e administração de ambientes isolados por meio de containers.",
    organization: "Full Cycle",
    certificateCode: "980564f0-73c5-42db-b544-efb32e4553dc",
    period: "29/05/2024 a 28/06/2024",
    hours: "21 horas",
    instructors: "Full Cycle, Wesley Willians",
    url: "https://fullcycle.com.br/certificado/980564f0-73c5-42db-b544-efb32e4553dc",
  },
  {
    id: "6",
    title: "SOLID Express",
    description:
      "Curso sobre os cinco princípios de design SOLID para desenvolvimento de software de alta qualidade.",
    organization: "Full Cycle",
    certificateCode: "31df4f3b-2534-4b1f-bedd-6d84142450b7",
    period: "03/06/2024 a 03/06/2024",
    hours: "3 horas",
    instructors: "Full Cycle, Wesley Willians",
    url: "https://fullcycle.com.br/certificado/31df4f3b-2534-4b1f-bedd-6d84142450b7",
  },
  {
    id: "7",
    title: "Domain Driven Design",
    description:
      "Curso sobre DDD para projetar e construir softwares complexos alinhados ao negócio.",
    organization: "Full Cycle",
    certificateCode: "04b1cd53-06c0-4a9a-8b9f-59cdb4efb1ee",
    period: "28/06/2024 a 24/07/2024",
    hours: "6 horas",
    instructors: "Full Cycle, Wesley Willians",
    url: "https://fullcycle.com.br/certificado/04b1cd53-06c0-4a9a-8b9f-59cdb4efb1ee",
  },
  {
    id: "8",
    title: "Arquitetura Hexagonal (Ports and Adapters)",
    description:
      "Curso sobre Arquitetura Hexagonal para organizar aplicações em camadas desacopladas com responsabilidades claras.",
    organization: "Full Cycle",
    certificateCode: "cb6d048a-cb83d-4f3e-a818-704ea752c1ee",
    period: "01/08/2024 a 22/08/2024",
    hours: "18 horas",
    instructors: "Full Cycle, Wesley Willians",
    url: "https://fullcycle.com.br/certificado/cb6d048a-cb83d-4f3e-a818-704ea752c1ee",
  },
  {
    id: "9",
    title: "DDD: Modelagem Tática e Patterns",
    description:
      "Curso sobre DDD: Modelagem Tática e Patterns para modelar software utilizando os blocos de construção do DDD.",
    organization: "Full Cycle",
    certificateCode: "292e73f1-57cc-47c8-923a-145f3e984d12",
    period: "28/06/2024 a 02/08/2024",
    hours: "34 horas",
    instructors: "Full Cycle, Wesley Willians",
    url: "https://fullcycle.com.br/certificado/292e73f1-57cc-47c8-923a-145f3e984d12",
  },
  {
    id: "10",
    title: "React JS com Redux, Firebase e TypeScript",
    description:
      "Curso sobre React JS com uso de Redux, Firebase e TypeScript para desenvolvimento de aplicações modernas e escaláveis.",
    organization: "Udemy",
    instructors: "Ivan Lourenço Gomes",
    certificateCode: "UC-b8c2ecca-f602-4d3a-b054-5b29ae688d24",
    period: "24/04/2024",
    hours: "12,5 horas",
    url: "https://www.udemy.com/certificate/UC-b8c2ecca-f602-4d3a-b054-5b29ae688d24/",
  },
  {
    id: "11",
    title: "Arquitetura de Sistemas Monolíticos",
    description:
      "Curso sobre Arquitetura de Sistemas Monolíticos para construção de monolitos robustos e sustentáveis.",
    organization: "Full Cycle",
    certificateCode: "88ec33cb-3806-45d0-bdd7-7b3ba1341507",
    period: "09/08/2024 a 25/10/2024",
    hours: "10 horas",
    instructors: "Full Cycle, Wesley Willians",
    url: "https://fullcycle.com.br/certificado/88ec33cb-3806-45d0-bdd7-7b3ba1341507",
  },
  {
    id: "12",
    title: "EDA - Event Driven Architecture",
    description:
      "Curso sobre EDA para uso de comunicação assíncrona na criação de sistemas distribuídos com baixo acoplamento.",
    organization: "Full Cycle",
    certificateCode: "cacc6fc7-66cd-43de-8ec6-41d24724f2d7",
    period: "23/08/2024 a 29/11/2024",
    hours: "10 horas",
    instructors: "Full Cycle, Wesley Willians",
    url: "https://fullcycle.com.br/certificado/cacc6fc7-66cd-43de-8ec6-41d24724f2d7",
  },
  {
    id: "13",
    title: "Fundamentos da arquitetura de software",
    description:
      "Performance, Escalabilidade e Resiliência são fundamentos essenciais para que um software seja construido da forma correta. É necessário entender os conceitos de fundamentos de arquitetura de software para se projetar e construir boas aplicações.",
    organization: "Full Cycle",
    certificateCode: "af8d2c18-ad1f-424f-8c59-eb98037fb550",
    period: "03/06/2024 a 21/08/2025",
    hours: "15 horas",
    instructors: "Full Cycle, Wesley Willians",
    url: "https://fullcycle.com.br/certificado/af8d2c18-ad1f-424f-8c59-eb98037fb550",
  },
  {
    id: "14",
    title: "Admin catalogo de vídeo - Codeflix - React.js (Front-end)",
    description:
      "Vamos criar o painel administrativo para a gestão de conteúdos para a CodeFlix.",
    organization: "Full Cycle",
    certificateCode: "4894c404-7f33-4638-ab7c-e0d87a66f518",
    period: "10/12/2024 a 16/07/2025",
    hours: "75 horas",
    instructors: "Full Cycle, Vitor Alencar",
    url: "https://fullcycle.com.br/certificado/4894c404-7f33-4638-ab7c-e0d87a66f518",
  },
  {
    id: "15",
    title: "Portal do usuário - Codeflix - (React.js, Next.js) (Front-end)",
    description: "Vamos criar a interface do usuário para a CodeFlix.",
    organization: "Full Cycle",
    certificateCode: "7a4a19dd-f2b0-49e9-9c11-365df6162256",
    period: "03/06/2024 a 04/08/2025",
    hours: "36 horas",
    instructors: "Full Cycle, Vitor Alencar",
    url: "https://fullcycle.com.br/certificado/7a4a19dd-f2b0-49e9-9c11-365df6162256",
  },
  {
    id: "16",
    title: "Admin catalogo de vídeo - Codeflix - Java (Back-end)",
    description:
      "Vamos criar todo backend para a para a gestão de conteúdos para a CodeFlix, utilizando Java.",
    organization: "Full Cycle",
    certificateCode: "2d515bc7-a6ee-4c4f-8ec7-52e03850fc32",
    period: "29/05/2024 a 12/03/2025",
    hours: "140 horas",
    instructors: "Full Cycle, Gabriel @deploydesexta.",
    url: "https://fullcycle.com.br/certificado/2d515bc7-a6ee-4c4f-8ec7-52e03850fc32",
  },
  {
    id: "17",
    title: "Angular 9 + Spring Boot 2.2: Fullstack Completo e Atualizado",
    description:
      "Curso Fullstack com Angular 9 e Spring Boot 2.2 para desenvolvimento de aplicações web completas e atualizadas.",
    organization: "Udemy",
    certificateCode: "UC-9b254497-43ce-4804-8877-c6580424f40b",
    period: "10/04/2024",
    hours: "20 horas",
    instructors: "Douglis Sousa",
    url: "https://www.udemy.com/certificate/UC-9b254497-43ce-4804-8877-c6580424f40b/",
  },
  {
    id: "18",
    title: "Desenvolvimento Web Avançado com PHP, Laravel e Vue.JS",
    description:
      "Curso avançado de desenvolvimento web utilizando o ecossistema PHP com o framework Laravel no back-end e Vue.JS no front-end.",
    organization: "Udemy",
    certificateCode: "UC-b06ae732-90c3-4e8a-aa1a-0b1a91de1e19",
    period: "22/08/2025",
    hours: "57 horas",
    instructors: "Jorge Sant Ana",
    url: "https://www.udemy.com/certificate/UC-b06ae732-90e3-4e8a-aa1a-0b1a913e1e19/",
  },
];
